name: Check for new Project Repos

on:
  push:
    branches:
      - main  
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-project-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update project repositories
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
        run: |
          npm install -g meta
          ./scripts/update.sh
          echo REPOS_ADDED=$(git diff --unified=0 .gitignore | grep '+/' | cut -f2 -d'/' | paste -sd ',' - | sed "s/,/, /g" | sed 's/\(.*\),/\1 and/') >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Added ${{ env.REPOS_ADDED }}.
          delete-branch: true
          title: 'Added ${{ env.REPOS_ADDED }}.'
          body: |
            Added ${{ env.REPOS_ADDED }}.
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"